name: e_commerce
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.7
  flutter_riverpod: ^2.6.1
  device_preview: ^1.2.0
  persistent_bottom_nav_bar: ^6.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  lottie: ^3.3.1
  supabase_flutter: ^2.9.0
  path_provider: ^2.1.5
  crop_image: ^1.0.16
  dio: ^5.8.0+1
  flutter_hooks: ^0.21.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
 

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lotties/
    - .env

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Thin.otf
          weight: 100
        - asset: assets/fonts/Metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Metropolis-Black.otf
          weight: 900
